name: environment_avila26
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2024.8.30=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libblas=3.9.0=25_linux64_openblas
  - libcblas=3.9.0=25_linux64_openblas
  - libffi=3.4.2=h7f98852_5
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgfortran=14.2.0=h69a702a_1
  - libgfortran5=14.2.0=hd5240d6_1
  - libgomp=14.2.0=h77fa898_1
  - liblapack=3.9.0=25_linux64_openblas
  - libnsl=2.0.1=hd590300_0
  - libopenblas=0.3.28=pthreads_h94d23a6_1
  - libsqlite=3.47.0=hadc24fc_1
  - libstdcxx=14.2.0=hc0a3c3a_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=he02047a_1
  - numpy=2.1.3=py310hd6e36ab_0
  - openssl=3.4.0=hb9d3cd8_0
  - packaging=24.2=pyhd8ed1ab_2
  - pandas=2.2.3=py310h5eaa309_1
  - pip=24.3.1=pyh8b19718_0
  - python=3.10.15=h4a871b0_2_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-tzdata=2024.2=pyhd8ed1ab_1
  - python_abi=3.10=5_cp310
  - pytz=2024.1=pyhd8ed1ab_0
  - readline=8.2=h8228510_1
  - setuptools=75.6.0=pyhff2d567_1
  - six=1.16.0=pyhd8ed1ab_1
  - tk=8.6.13=noxft_h4845f30_101
  - tzdata=2024b=hc8b5060_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - xarray=2024.11.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - pip:
      - anyio==4.6.2.post1
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==24.2.0
      - babel==2.16.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - blosc2==2.7.1
      - bokeh==3.7.0
      - certifi==2024.8.30
      - cf-xarray==0.10.0
      - cffi==1.17.1
      - cfgrib==0.9.15.0
      - cftime==1.6.4.post1
      - charset-normalizer==3.4.0
      - click==8.1.8
      - cloudpickle==3.1.1
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - cython==3.0.11
      - dask==2025.2.0
      - dask-jobqueue==0.9.0
      - debugpy==1.8.9
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distributed==2025.2.0
      - eccodes==2.40.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - findlibs==0.1.0
      - fonttools==4.55.1
      - formulaic==1.0.2
      - fqdn==1.5.1
      - fsspec==2025.2.0
      - geopandas==1.0.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.0
      - idna==3.10
      - importlib-metadata==8.6.1
      - interface-meta==1.3.0
      - ipykernel==6.29.5
      - ipython==8.30.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.6
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - kiwisolver==1.4.7
      - linearmodels==6.1
      - locket==1.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.3
      - matplotlib-inline==0.1.7
      - mistune==3.0.2
      - msgpack==1.1.0
      - mypy-extensions==1.0.0
      - narwhals==1.30.0
      - nbclient==0.10.1
      - nbconvert==7.16.4
      - nbformat==5.10.4
      - nc-time-axis==1.4.1
      - ndindex==1.9.2
      - nest-asyncio==1.6.0
      - netcdf4==1.7.2
      - notebook==7.3.3
      - notebook-shim==0.2.4
      - numcodecs==0.13.1
      - numexpr==2.10.2
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.48
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - py-cpuinfo==9.0.0
      - pycparser==2.22
      - pygments==2.18.0
      - pyhdfe==0.2.0
      - pyogrio==0.10.0
      - pyparsing==3.2.0
      - pyproj==3.7.0
      - python-json-logger==2.0.7
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.35.1
      - requests==2.32.3
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rpds-py==0.22.1
      - scipy==1.14.1
      - send2trash==1.8.3
      - setuptools-scm==8.1.0
      - shapely==2.0.7
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - tables==3.10.1
      - tblib==3.0.0
      - terminado==0.18.1
      - tinycss2==1.4.0
      - tomli==2.2.1
      - toolz==1.0.0
      - tornado==6.4.2
      - traitlets==5.14.3
      - types-python-dateutil==2.9.0.20241003
      - typing-extensions==4.12.2
      - uri-template==1.3.0
      - urllib3==2.2.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wrapt==1.17.0
      - xagg==0.3.2.4
      - xyzservices==2025.1.0
      - zarr==2.18.3
      - zict==3.0.0
      - zipp==3.21.0
prefix: /storage/home/cta5244/mambaforge/envs/environment_avila26
